/**
 * ACTIONS
 */
export const CHANGE_CARD = 'CHANGE_CARD'
export const START_GAME = 'START_GAME'
export const END_GAME = 'END_GAME'
export const INCREMENT_TURN = 'INCREMENT_TURN'
export const CREATE_GAME_START = 'CREATE_GAME_START'
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS'
export const CREATE_GAME_FAIL = 'CREATE_GAME_FAIL'
export const GET_CURRENT_GAME = 'GET_CURRENT_GAME'
export const GET_CURRENT_GAME_SUCCESS = 'GET_CURRENT_GAME_SUCCESS'
export const GET_CURRENT_GAME_FAIL = 'GET_CURRENT_GAME_FAIL'
export const RESTART_GAME = 'RESTART_GAME' 
export const ADD_CARDBOARD = 'ADD_CARDBOARD'
export const SET_GAME_HISTORY = 'SET_GAME_HISTORY'

export const VALIDATE_FOLIO_START = 'VALIDATE_FOLIO_START'
export const VALIDATE_FOLIO_SUCCESS = 'VALIDATE_FOLIO_SUCCESS'
export const VALIDATE_FOLIO_FAIL = 'VALIDATE_FOLIO_FAIL'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'
export const SET_GAME = 'SET_GAME'
export const SET_CONECTION_ID = 'SET_CONECTION_ID'

export const CREATE_CARDBOARD_START = 'CREATE_CARDBOARD_START'
export const CREATE_CARDBOARD_SUCCESS = 'CREATE_CARDBOARD_SUCCESS'
export const CREATE_CARDBOARD_FAIL = 'CREATE_CARDBOARD_FAIL'
export const SEARCH_CARDBOARD_START = 'SEARCH_CARDBOARD_START'
export const SEARCH_CARDBOARD_SUCCESS = 'SEARCH_CARDBOARD_SUCCESS'
export const SEARCH_CARDBOARD_FAIL = 'SEARCH_CARDBOARD_FAIL'
export const GET_CARDBOARDS_TOTAL_START = 'GET_CARDBOARDS_TOTAL_START'
export const GET_CARDBOARDS_TOTAL_SUCCESS = 'GET_CARDBOARDS_TOTAL_SUCCESS'
export const GET_CARDBOARDS_TOTAL_FAIL = 'GET_CARDBOARDS_TOTAL_FAIL' 
export const DELETE_CARDBOARD_START = 'DELETE_CARDBOARD_START'
export const DELETE_CARDBOARD_SUCCESS = 'DELETE_CARDBOARD_SUCCESS'
export const DELETE_CARDBOARD_FAIL = 'DELETE_CARDBOARD_FAIL'

export const ADD_CARDBOARD_TO_VALIDATE = 'ADD_CARDBOARD_TO_VALIDATE'
export const REMOVE_CARDBOARD_TO_VALIDATE = 'REMOVE_CARDBOARD_TO_VALIDATE'
export const ADD_CARDBOARD_SINGLE_LINE_WINNER = 'ADD_CARDBOARD_SINGLE_LINE_WINNER'
export const REMOVE_ALL_CARDBOARDS_TO_VALIDATE = 'REMOVE_ALL_CARDBOARDS_TO_VALIDATE'

