/**
 * ACTIONS
 */
export const CHANGE_CARD = 'CHANGE_CARD'
export const START_GAME = 'START_GAME'
export const END_GAME = 'END_GAME'
export const INCREMENT_TURN = 'INCREMENT_TURN'
export const CREATE_GAME_START = 'CREATE_GAME_START'
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS'
export const CREATE_GAME_FAIL = 'CREATE_GAME_FAIL'
export const GET_CURRENT_GAME = 'GET_CURRENT_GAME'
export const GET_CURRENT_GAME_SUCCESS = 'GET_CURRENT_GAME_SUCCESS'
export const GET_CURRENT_GAME_FAIL = 'GET_CURRENT_GAME_FAIL' 

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'
